# Generated by Django 3.1.3 on 2021-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_galery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
