# Generated by Django 3.1.3 on 2021-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_information_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
