# Generated by Django 3.1.3 on 2021-05-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_icon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
