# Generated by Django 3.1.3 on 2021-05-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_icon_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='icon',
        ),
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
