# Generated by Django 3.1.3 on 2021-05-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210505_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=300)),
                ('mini_description', models.CharField(blank=True, max_length=500)),
                ('address_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
