# Generated by Django 3.1.3 on 2021-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210505_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
