# Generated by Django 3.1.3 on 2021-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210506_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='vide_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
