# Generated by Django 3.1.3 on 2021-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210509_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='code',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='languages',
            name='extra_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
