# Generated by Django 3.1.3 on 2021-05-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210509_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='acredatsiya',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='adistemelikkabinet',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='aqparat',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='baza',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='biliktilik',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='birlestikter',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='comentary',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='galery',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='icon',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='information',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='jasmaman',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='jetistikter',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='jumysqaornalasu',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='karta',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='kollejtarihi',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='license',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='news',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='oquadisteme',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='oquurdisi',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='qabyldau',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='qashyqtyq',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='qurylym',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='register',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='sabaqkeste',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='saualnama',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='seriktester',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='slider',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='studentjetistik',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='video',
            name='lang',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
    ]
