# Generated by Django 3.1.3 on 2021-05-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210509_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('lang', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages')),
            ],
        ),
    ]
