# Generated by Django 3.1.3 on 2021-05-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_transvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='knopka',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='knopka_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
