# Generated by Django 3.1.3 on 2021-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_talapker'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
