# Generated by Django 3.1.3 on 2021-06-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_specialty_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qabyldau',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
