# Generated by Django 3.1.3 on 2021-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210601_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='biliktilik',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
