# Generated by Django 3.1.3 on 2021-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='kollejtarihi',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
