# Generated by Django 3.1.3 on 2021-06-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_adistemelikkabinet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasmaman',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kenesjospary',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
