# Generated by Django 3.1.3 on 2021-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210601_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='jetistikter',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
