# Generated by Django 3.1.3 on 2021-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_oqu'),
    ]

    operations = [
        migrations.AddField(
            model_name='oquurdisi',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
