# Generated by Django 3.1.3 on 2021-06-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_studentjetistik_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttikkenes',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
