# Generated by Django 3.1.3 on 2021-06-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_studenttikkenes_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='mini_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
