# Generated by Django 3.1.3 on 2021-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210601_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
