# Generated by Django 3.1.3 on 2021-06-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_license_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tulekter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='upload')),
                ('title', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('link', models.TextField(blank=True)),
                ('lang', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.languages')),
            ],
        ),
    ]
