# Generated by Django 3.1.3 on 2021-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_tulekter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumysqaornalasu',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
