# Generated by Django 3.1.3 on 2021-06-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_jumysqaornalasu_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriktester',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
