# Generated by Django 3.1.3 on 2021-06-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_seriktester_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='saualnama',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
