# Generated by Django 3.1.3 on 2021-06-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_saualnama_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
