# Generated by Django 3.1.3 on 2021-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_license_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='word',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
