# Generated by Django 3.1.3 on 2021-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_license_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='pdf_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='license',
            name='word_title',
            field=models.TextField(blank=True),
        ),
    ]
