# Generated by Django 3.1.3 on 2021-06-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210602_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='adistemelikkabinet',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adistemelikkabinet',
            name='pdf_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adistemelikkabinet',
            name='word',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adistemelikkabinet',
            name='word_title',
            field=models.TextField(blank=True),
        ),
    ]
