# Generated by Django 3.1.3 on 2021-06-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20210602_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttikkenes',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studenttikkenes',
            name='pdf_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studenttikkenes',
            name='word',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studenttikkenes',
            name='word_title',
            field=models.TextField(blank=True),
        ),
    ]
